# Generated by Django 6.0.3 on 2026-04-07 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('education', 'Education'), ('health', 'Healthcare'), ('environment', 'Environment'), ('food', 'Food & Nutrition'), ('women', 'Women Empowerment'), ('disaster', 'Disaster Relief'), ('animal', 'Animal Welfare')], max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('founded_year', models.IntegerField(default=2020)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('logo_initial', models.CharField(default='NGO', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('amount_required', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_raised', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needs', to='core.ngo')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type', models.CharField(choices=[('monetary', 'Monetary'), ('material', 'Material')], default='monetary', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('material_description', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
                ('need', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='core.need')),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='core.ngo')),
            ],
        ),
        migrations.CreateModel(
            name='UtilizationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('amount_used', models.DecimalField(decimal_places=2, max_digits=12)),
                ('impact_description', models.TextField()),
                ('beneficiaries_count', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('need', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.need')),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.ngo')),
            ],
        ),
    ]
